# frozen_string_literal: true

COLOMBIA = :colombia
VENEZUELA = :venezuela
PANAMA = :panama

MOUNTAIN = :mountain
GRASSLAND = :grassland
FOREST = :forest

GOVT_FACTION = :govt
FARC_FACTION = :farc
CARTEL_FACTION = :cartel
AUC_FACTION = :auc

FACTIONS = [GOVT_FACTION, FARC_FACTION, CARTEL_FACTION, AUC_FACTION].freeze

TROOPS = :troops
POLICE = :police
GUERRILLAS = :guerrillas
BASES = :bases
SHIPMENTS = :shipments

FORCES = {
  GOVT_FACTION => [TROOPS, POLICE, GUERRILLAS, BASES],
  FARC_FACTION => [GUERRILLAS, BASES],
  AUC_FACTION => [GUERRILLAS, BASES],
  CARTEL_FACTION => [GUERRILLAS, BASES]
}.freeze

CAPABILITY_NONE = :cap_none
CAPABILITY_CARTEL = :cap_cartel
CAPABILITY_GOVT = :cap_govt
CAPABILITY_MOMENTUM = :cap_momentum

CONTROL_NONE = :none
CONTROL_GOVT = :control_govt
CONTROL_FARC = :control_farc
CONTROL_FARC_ZONE = :control_farc_zone

SUPPORT_ACTIVE = 5
SUPPORT_PASSIVE = 4
SUPPORT_NEUTRAL = 3
SUPPORT_PASSIVE_OPPOSE = 2
SUPPORT_ACTIVE_OPPOSE = 1

CARTEL_ACTION_FLIP = 1
CARTEL_ACTION_REPLACE = 2
CARTEL_ACTION_ADD = 3
CARTEL_ACTION_CULTIVATE = 4
CARTEL_ACTION_PASS = 9

CITY = :city
PROVINCE = :province
LOC = :loc

ACTION_NOT_AVAILABLE = :not_available
PRIORITY_TOP = 5
PRIORITY_HIGH = 4
PRIORITY_NORMAL = 3
PRIORITY_LOW = 2
PRIORITY_BOTTOM = 1
PRIORITY_AVOID = 0
